/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kyi_andwebsrv_MainActivity */

#ifndef _Included_kyi_andwebsrv_MainActivity
#define _Included_kyi_andwebsrv_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef kyi_andwebsrv_MainActivity_MODE_PRIVATE
#define kyi_andwebsrv_MainActivity_MODE_PRIVATE 0L
#undef kyi_andwebsrv_MainActivity_MODE_WORLD_READABLE
#define kyi_andwebsrv_MainActivity_MODE_WORLD_READABLE 1L
#undef kyi_andwebsrv_MainActivity_MODE_WORLD_WRITEABLE
#define kyi_andwebsrv_MainActivity_MODE_WORLD_WRITEABLE 2L
#undef kyi_andwebsrv_MainActivity_MODE_APPEND
#define kyi_andwebsrv_MainActivity_MODE_APPEND 32768L
#undef kyi_andwebsrv_MainActivity_BIND_AUTO_CREATE
#define kyi_andwebsrv_MainActivity_BIND_AUTO_CREATE 1L
#undef kyi_andwebsrv_MainActivity_BIND_DEBUG_UNBIND
#define kyi_andwebsrv_MainActivity_BIND_DEBUG_UNBIND 2L
#undef kyi_andwebsrv_MainActivity_BIND_NOT_FOREGROUND
#define kyi_andwebsrv_MainActivity_BIND_NOT_FOREGROUND 4L
#undef kyi_andwebsrv_MainActivity_CONTEXT_INCLUDE_CODE
#define kyi_andwebsrv_MainActivity_CONTEXT_INCLUDE_CODE 1L
#undef kyi_andwebsrv_MainActivity_CONTEXT_IGNORE_SECURITY
#define kyi_andwebsrv_MainActivity_CONTEXT_IGNORE_SECURITY 2L
#undef kyi_andwebsrv_MainActivity_CONTEXT_RESTRICTED
#define kyi_andwebsrv_MainActivity_CONTEXT_RESTRICTED 4L
#undef kyi_andwebsrv_MainActivity_RESULT_CANCELED
#define kyi_andwebsrv_MainActivity_RESULT_CANCELED 0L
#undef kyi_andwebsrv_MainActivity_RESULT_OK
#define kyi_andwebsrv_MainActivity_RESULT_OK -1L
#undef kyi_andwebsrv_MainActivity_RESULT_FIRST_USER
#define kyi_andwebsrv_MainActivity_RESULT_FIRST_USER 1L
#undef kyi_andwebsrv_MainActivity_DEFAULT_KEYS_DISABLE
#define kyi_andwebsrv_MainActivity_DEFAULT_KEYS_DISABLE 0L
#undef kyi_andwebsrv_MainActivity_DEFAULT_KEYS_DIALER
#define kyi_andwebsrv_MainActivity_DEFAULT_KEYS_DIALER 1L
#undef kyi_andwebsrv_MainActivity_DEFAULT_KEYS_SHORTCUT
#define kyi_andwebsrv_MainActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef kyi_andwebsrv_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define kyi_andwebsrv_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef kyi_andwebsrv_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define kyi_andwebsrv_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     kyi_andwebsrv_MainActivity
 * Method:    nativeQueryInternet
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kyi_andwebsrv_MainActivity_nativeQueryInternet
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
