/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kyi_andwebsrv_MainActivity_NatPMPClient */

#ifndef _Included_kyi_andwebsrv_MainActivity_NatPMPClient
#define _Included_kyi_andwebsrv_MainActivity_NatPMPClient
#ifdef __cplusplus
extern "C" {
#endif
#undef kyi_andwebsrv_MainActivity_NatPMPClient_MIN_PRIORITY
#define kyi_andwebsrv_MainActivity_NatPMPClient_MIN_PRIORITY 1L
#undef kyi_andwebsrv_MainActivity_NatPMPClient_NORM_PRIORITY
#define kyi_andwebsrv_MainActivity_NatPMPClient_NORM_PRIORITY 5L
#undef kyi_andwebsrv_MainActivity_NatPMPClient_MAX_PRIORITY
#define kyi_andwebsrv_MainActivity_NatPMPClient_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
